const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let currentId=null,currentResult=null,pollTimer=null,filter='All';
const labels=['Pages Tested','Links Tested','Forms Tested','Images Tested','JavaScript Errors','Broken Links'],icons=['▦','↗','▤','▧','⌘','⊘'],keys=['pagesTested','linksTested','formsTested','imagesTested','javascriptErrors','brokenLinks'];
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');
$('#scanForm').addEventListener('submit',async e=>{e.preventDefault();clearInterval(pollTimer);$('#notice').classList.add('hidden');$('#results').classList.add('hidden');$('#progressArea').classList.remove('hidden');$('#runBtn').disabled=true;$('#progressBar').style.width='2%';$('#statusText').textContent='Initializing browser...';$('#percentText').textContent='1%';
 try{const r=await fetch('/api/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:$('#urlInput').value.trim()})}),d=await r.json();if(!r.ok)throw Error(d.error||'Could not start scan');currentId=d.id;pollTimer=setInterval(poll,700);poll()}catch(err){showError(err.message)}});
async function poll(){if(!currentId)return;try{let r=await fetch(`/api/scan/${currentId}`),j=await r.json();$('#statusText').textContent=j.status||'Working...';$('#percentText').textContent=`${j.progress||0}%`;$('#progressBar').style.width=`${j.progress||0}%`;if(j.done){clearInterval(pollTimer);$('#runBtn').disabled=false;$('#stopBtn').textContent='Stop test';if(j.result){currentResult=j.result;render(j.result);$('#results').classList.remove('hidden')}else showError(j.error||'Scan failed')}}catch(e){clearInterval(pollTimer);showError(e.message)}}
function showError(msg){$('#runBtn').disabled=false;$('#notice').textContent=msg;$('#notice').classList.remove('hidden')}
$('#stopBtn').onclick=async()=>{if(currentId){await fetch(`/api/scan/${currentId}/stop`,{method:'POST'});$('#statusText').textContent='Stop requested...';$('#stopBtn').textContent='Stopping'}};
function render(r){const s=r.stats,issues=r.issues;$('#statsGrid').innerHTML=keys.map((k,i)=>`<div class="stat-card"><span class="stat-icon">${icons[i]}</span><div class="stat-value">${s[k]??'Not Tested'}</div><div class="stat-label">${labels[i]}</div></div>`).join('');$('#issueCount').textContent=`${issues.length} finding${issues.length===1?'':'s'}`;$('#severityGrid').innerHTML=['Critical','High','Medium','Low'].map(x=>`<div class="severity-card"><span class="severity-name ${x.toLowerCase()}">${x}</span><b class="severity-count ${x.toLowerCase()}">${issues.filter(i=>i.severity===x).length}</b></div>`).join('');renderRows();const a=r.summary;$('#aiContent').innerHTML=`<div class="ai-block"><p>${esc(a.summary)}</p></div><div class="ai-kicker">POTENTIAL IMPACT</div><p class="limit-content">${esc(a.impact)}</p><div class="ai-kicker">PAGES REQUIRING ATTENTION</div><div class="ai-pages">${a.pages.length?a.pages.map(p=>`<span>${esc(p)}</span>`).join(''):'<span>No affected pages identified</span>'}</div><div class="ai-kicker">SUGGESTED NEXT STEPS</div><p class="limit-content">${esc(a.suggestions)}</p><div class="ai-kicker">QUALITY OBSERVATION</div><p class="limit-content">${esc(a.quality)}</p>`;$('#limitations').innerHTML=r.limitations.length?r.limitations.map(x=>`<div class="limit-item">${esc(x)}</div>`).join(''):'All scheduled checks completed.';$('#reportText').textContent=r.report}
function renderRows(){let list=currentResult.issues.filter(x=>filter==='All'||x.severity===filter);$('#issueRows').innerHTML=list.map((x,i)=>`<tr><td>#${String(i+1).padStart(2,'0')}</td><td><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.url)}</a></td><td><span class="desc">${esc(x.description)}</span></td><td>${esc(x.category)}</td><td><span class="badge ${esc(x.severity)}">${esc(x.severity)}</span></td><td><div class="evidence">${esc(x.evidence)}</div><div class="fix">Fix: ${esc(x.fix)}</div></td></tr>`).join('');$('#emptyIssues').classList.toggle('hidden',list.length!==0);$('.table-wrap').classList.toggle('hidden',list.length===0)}
$('#filters').onclick=e=>{if(!e.target.matches('.filter'))return;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b===e.target));filter=e.target.dataset.filter;if(currentResult)renderRows()};$('#detailsBtn').onclick=()=>document.querySelector('.issues-panel').scrollIntoView({behavior:'smooth'});
function save(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}$('#downloadBtn').onclick=()=>currentResult&&save('website-test-report.txt',currentResult.report,'text/plain');$('#jsonBtn').onclick=()=>currentResult&&save('website-test-results.json',JSON.stringify(currentResult,null,2),'application/json');$('#csvBtn').onclick=()=>{if(!currentResult)return;let quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';let rows=[['Issue','Page URL','Description','Category','Severity','Evidence','Recommended Fix'],...currentResult.issues.map((x,i)=>[i+1,x.url,x.description,x.category,x.severity,x.evidence,x.fix])];save('website-test-issues.csv',rows.map(row=>row.map(quote).join(',')).join('\r\n'),'text/csv')};$('#copyBtn').onclick=async()=>{if(currentResult){await navigator.clipboard.writeText(currentResult.report);$('#copyBtn').textContent='Copied';setTimeout(()=>$('#copyBtn').textContent='Copy',1500)}};$('#clearBtn').onclick=()=>{currentResult=null;$('#results').classList.add('hidden');$('#progressArea').classList.add('hidden');$('#notice').classList.add('hidden');$('#urlInput').value='';$('#progressBar').style.width='0';filter='All'};
